# Generated by Django 5.2 on 2025-05-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehub', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images/'),
        ),
    ]
